// media/main.js
// This script handles the client-side logic for the Ollama Collaborators webview.
// It manages UI interactions, communication with the VSCode extension backend (extension.ts),
// and dynamically updates the webview content based on messages received from the extension.
// Key responsibilities include:
// - Sending user prompts and agent configurations to the extension.
// - Displaying conversation history between the user and agents.
// - Handling UI for Autonomous Mode (starting, stopping, monitoring plans).
// - Adding action buttons to code blocks generated by agents.
// - Displaying status messages, errors, and file operation feedback.


// Get a reference to the VS Code API so we can post messages back to the extension
const vscode = acquireVsCodeApi();

/**
 * Basic HTML sanitizer to prevent XSS from simple string injections.
 * It creates a temporary div, sets its textContent (which escapes HTML),
 * and then reads its innerHTML.
 * @param {string} str The string to sanitize.
 * @returns {string} The sanitized string.
 */
function sanitizeHTML(str) {
    if (typeof str !== 'string') return ''; // Handle non-string inputs gracefully
    const temp = document.createElement('div');
    temp.textContent = str;
    return temp.innerHTML;
}

/**
 * Retrieves or creates a DOM element for displaying an individual action's status
 * within the autonomous plan display area.
 * @param {string | undefined} actionId The unique ID of the action.
 * @param {number} index The index of the action in the plan.
 * @param {HTMLElement} planDisplay The parent DOM element where action items are displayed.
 * @returns {HTMLElement} The existing or newly created div for the action.
 */
function getOrCreateActionElement(actionId, index, planDisplay) {
    // Use a combination of actionId (if available) and index for a more unique element ID
    const elementId = `action-${actionId || index}`;
    let actionDiv = document.getElementById(elementId);
    if (!actionDiv) {
        actionDiv = document.createElement('div');
        actionDiv.id = elementId;
        actionDiv.className = 'action-item'; // General class for styling
        planDisplay.appendChild(actionDiv); // Append new actions to the end of the plan display
    }
    return actionDiv;
}

// Keep track of ongoing streaming messages for regular agent chat
let agentStreamingMessages = {};

// --- Initialization on Webview Load ---
// This block executes when the webview's HTML content has fully loaded.
// It retrieves references to key DOM elements and sets up initial event listeners.
window.addEventListener('load', () => {
    // Standard chat UI elements
    const sendButton = document.getElementById('sendPromptButton');
    const userPromptInput = document.getElementById('userPrompt');

    // Autonomous Mode UI elements
    const autonomousModeStatusSpan = document.getElementById('autonomousModeStatus');
    const shellExecutionStatusSpan = document.getElementById('shellExecutionStatus');
    const autonomousProjectPromptInput = document.getElementById('autonomousProjectPrompt');
    const startAutonomousTaskButton = document.getElementById('startAutonomousTaskButton');
    const stopAutonomousTaskButton = document.getElementById('stopAutonomousTaskButton');
    const autonomousPlanDisplay = document.getElementById('autonomousPlanDisplay');

    // Event listener for the main 'Send' button in the chat interface
    if (sendButton && userPromptInput) {
        sendButton.addEventListener('click', () => {
            const promptText = userPromptInput.value;
            // Get current agent configurations from the input fields
            const agentOneBaseURL = document.getElementById('agentOneBaseURL').value;
            const agentOneModel = document.getElementById('agentOneModel').value;
            const agentTwoBaseURL = document.getElementById('agentTwoBaseURL').value;
            const agentTwoModel = document.getElementById('agentTwoModel').value;

            if (promptText) {
                // Send the user's prompt and current agent configurations to the extension
                vscode.postMessage({
                    command: 'userPrompt',
                    text: promptText,
                    config: {
                        agent1: { baseURL: agentOneBaseURL, model: agentOneModel },
                        agent2: { baseURL: agentTwoBaseURL, model: agentTwoModel }
                    }
                });
                // Display the user's message in the conversation area
                const conversationDisplay = document.getElementById('conversation');
                const userMessageDiv = document.createElement('div');
                userMessageDiv.className = 'message user-message';
                userMessageDiv.textContent = `You: ${promptText}`; // Uses template literal, fine in JS
                if (conversationDisplay) {
                    conversationDisplay.appendChild(userMessageDiv);
                    conversationDisplay.scrollTop = conversationDisplay.scrollHeight; // Scroll to bottom
                }
                userPromptInput.value = ''; // Clear the input field
            }
        });
    } else {
        console.warn('Main prompt UI elements (sendButton, userPromptInput) not all found on load.');
    }

    // Event listener for the 'Start Autonomous Task' button
    if (startAutonomousTaskButton && autonomousProjectPromptInput && stopAutonomousTaskButton && autonomousPlanDisplay) {
        startAutonomousTaskButton.addEventListener('click', () => {
            const projectPrompt = autonomousProjectPromptInput.value;
            if (projectPrompt) {
                // Send the project prompt to the extension to start an autonomous task
                vscode.postMessage({ command: 'startAutonomousTask', projectPrompt: projectPrompt });
                // Update UI to reflect task starting
                startAutonomousTaskButton.disabled = true;
                stopAutonomousTaskButton.style.display = 'inline-block';
                autonomousPlanDisplay.innerHTML = ''; // Clear previous plan display
            } else {
                // Inform the user if the project prompt is empty
                vscode.postMessage({ command: 'showError', text: 'Please enter a project prompt for autonomous mode.'});
            }
        });

        // Event listener for the 'Stop Autonomous Task' button
        stopAutonomousTaskButton.addEventListener('click', () => {
            vscode.postMessage({ command: 'stopAutonomousTask' });
        });
    } else {
        console.warn("Autonomous mode UI elements (start/stop buttons, prompt, display) not all found on load.");
    }
});

// --- Message Handling from Extension ---
// This block listens for messages posted from the VSCode extension backend (extension.ts)
// and updates the webview UI accordingly.
window.addEventListener('message', event => {
    const message = event.data; // The data payload of the message from the extension
    const conversationDisplay = document.getElementById('conversation'); // For regular chat
    const autonomousPlanDisplay = document.getElementById('autonomousPlanDisplay'); // For autonomous mode action display

    // Ensure at least one of the primary display areas is available
    if (!conversationDisplay && !autonomousPlanDisplay) {
        console.error("Neither conversationDisplay nor autonomousPlanDisplay element found in webview!");
        return;
    }
    // Some messages might target 'conversationDisplay' even if 'autonomousPlanDisplay' is the primary one for that command
    const targetDisplay = message.command.startsWith('autonomous') || message.command === 'displayAgentMessage' ? autonomousPlanDisplay : conversationDisplay;
    if (!targetDisplay) { // If the specific target for this message isn't there, log and potentially skip.
        console.error(`Target display for command '${message.command}' not found.`);
        // Depending on command, might still want to proceed if one display is missing but not the other.
        // For now, if the primary target for the command is missing, we might have issues.
    }


    // Process message based on its 'command' type
    switch (message.command) {
        // Handles incoming responses (or chunks of responses if streaming) from Ollama agents.
        case 'agentResponse':
            let agentMessageDiv;
            const agentKey = message.agentName;
            if (message.text === 'Thinking...' && !message.streaming) {
                // Handle "Thinking..." message: update or create a new div
                if (agentStreamingMessages[agentKey]) {
                    agentMessageDiv = agentStreamingMessages[agentKey];
                    agentMessageDiv.innerHTML = `<span class="agent-name">${sanitizeHTML(message.agentName)}: </span><span class="agent-response-text" style="font-style: italic;">Thinking...</span>`;
                } else {
                    agentMessageDiv = document.createElement('div');
                    agentMessageDiv.className = 'message agent-message';
                    agentMessageDiv.innerHTML = `<span class="agent-name">${sanitizeHTML(message.agentName)}: </span><span class="agent-response-text" style="font-style: italic;">Thinking...</span>`;
                    if (conversationDisplay) conversationDisplay.appendChild(agentMessageDiv);
                    agentStreamingMessages[agentKey] = agentMessageDiv;
                }
            } else if (message.streaming && agentStreamingMessages[agentKey]) {
                // Update existing message div with new streaming content
                agentMessageDiv = agentStreamingMessages[agentKey];
                const responseSpan = agentMessageDiv.querySelector('.agent-response-text');
                if (responseSpan) {
                    responseSpan.style.fontStyle = 'normal'; // Remove italic if it was "Thinking..."
                    responseSpan.textContent = message.fullResponseSoFar; // Update with accumulated content
                }
            } else {
                // New message or non-streaming final part, or first part of stream without prior "Thinking..."
                if (agentStreamingMessages[agentKey] && message.streaming) {
                     // This case handles a stream starting without a "Thinking..." message,
                     // or if the stream was somehow interrupted and restarted.
                     agentMessageDiv = agentStreamingMessages[agentKey];
                     const responseSpan = agentMessageDiv.querySelector('.agent-response-text');
                     if(responseSpan) {
                        responseSpan.style.fontStyle = 'normal';
                        responseSpan.textContent = message.fullResponseSoFar;
                     }
                } else {
                    // Create a new message div for non-streaming or initial stream part
                    agentMessageDiv = document.createElement('div');
                    agentMessageDiv.className = 'message agent-message';

                    const agentNameSpan = document.createElement('span');
                    agentNameSpan.className = 'agent-name';
                    agentNameSpan.textContent = `${sanitizeHTML(message.agentName)}: `;
                    agentMessageDiv.appendChild(agentNameSpan);

                    const agentResponseSpan = document.createElement('span');
                    agentResponseSpan.className = 'agent-response-text';
                    agentResponseSpan.textContent = message.streaming ? message.fullResponseSoFar : message.text;
                    agentMessageDiv.appendChild(agentResponseSpan);

                    if (conversationDisplay) conversationDisplay.appendChild(agentMessageDiv);

                    if (message.streaming) {
                         agentStreamingMessages[agentKey] = agentMessageDiv; // Store for subsequent stream updates
                    } else {
                        // If not streaming, it's a complete message. Check for code and add buttons.
                        const textContent = message.text || message.fullResponseSoFar || "";
                        if (textContent.includes('```')) {
                            addCodeActionButtons(agentMessageDiv, textContent);
                        }
                    }
                }
            }
            if (conversationDisplay) conversationDisplay.scrollTop = conversationDisplay.scrollHeight;
            break;
        // Finalizes a streaming agent response, potentially adding action buttons if it's code.
        case 'agentResponseDone':
            if (agentStreamingMessages[message.agentName]) {
                const doneDiv = agentStreamingMessages[message.agentName];
                const responseSpan = doneDiv.querySelector('.agent-response-text');
                if (responseSpan) {
                    doneDiv.style.fontStyle = 'normal'; // Ensure not stuck in italic
                    const textContent = responseSpan.textContent || "";
                    // Add action buttons if they haven't been added yet and content is code
                    if (!doneDiv.querySelector('.code-actions') && textContent.includes('```')) {
                         addCodeActionButtons(doneDiv, textContent);
                    }
                }
            }
            delete agentStreamingMessages[message.agentName]; // Clear for this agent
            if (conversationDisplay) conversationDisplay.scrollTop = conversationDisplay.scrollHeight;
            break;
        // Displays status messages (success/error) for file operations.
        case 'fileOperationStatus':
            const statusMessageDiv = document.createElement('div');
            statusMessageDiv.className = `message ${message.success ? 'file-op-success' : 'file-op-error'}`;
            statusMessageDiv.textContent = message.message;
            // File operation statuses are typically short and can go to the main conversation.
            if (conversationDisplay) {
                conversationDisplay.appendChild(statusMessageDiv);
                conversationDisplay.scrollTop = conversationDisplay.scrollHeight;
            }
            break;
        // Displays general error messages from the extension.
        case 'showError':
             const errorMessageDiv = document.createElement('div');
             errorMessageDiv.className = 'message error-message';
             errorMessageDiv.style.color = 'red'; // Standard error color
             errorMessageDiv.textContent = `ERROR: ${sanitizeHTML(message.text)}`;
             if (conversationDisplay) {
                conversationDisplay.appendChild(errorMessageDiv);
                conversationDisplay.scrollTop = conversationDisplay.scrollHeight;
             }
             break;

        // --- Cases for Autonomous Mode ---

        // Handles updates to settings (e.g., autonomous mode status) from the extension.
        case 'settingsUpdate':
            const autoModeStatusSpan = document.getElementById('autonomousModeStatus');
            const shellExecStatusSpan = document.getElementById('shellExecutionStatus');
            const autoProjectPromptInput = document.getElementById('autonomousProjectPrompt');
            const startAutoTaskButton = document.getElementById('startAutonomousTaskButton');

            if (autoModeStatusSpan) {
                autoModeStatusSpan.textContent = message.isAutonomousModeEnabled ? 'Enabled' : 'Disabled';
                autoModeStatusSpan.style.color = message.isAutonomousModeEnabled ? 'var(--vscode-terminal-ansiGreen)' : 'var(--vscode-terminal-ansiRed)';
            }
            if (shellExecStatusSpan) {
                shellExecStatusSpan.textContent = message.isShellExecutionEnabled ? 'Enabled' : 'Disabled';
                shellExecStatusSpan.style.color = message.isShellExecutionEnabled ? 'var(--vscode-terminal-ansiGreen)' : 'var(--vscode-terminal-ansiRed)';
            }
            // Enable/disable autonomous task input and button based on the master setting
            if (startAutoTaskButton && autoProjectPromptInput) {
                startAutoTaskButton.disabled = !message.isAutonomousModeEnabled;
                autoProjectPromptInput.disabled = !message.isAutonomousModeEnabled;
                if (!message.isAutonomousModeEnabled) {
                     autoProjectPromptInput.placeholder = "Enable 'ollamaCollaborators.enableAutonomousMode' in settings to use this feature.";
                } else {
                    autoProjectPromptInput.placeholder = "Describe the project or complex task for the agents...";
                }
            }
            break;
        // Updates the UI with the overall status of an autonomous plan execution.
        case 'autonomousPlanStatus': {
            const startButton = document.getElementById('startAutonomousTaskButton');
            const stopButton = document.getElementById('stopAutonomousTaskButton');
            const projectPromptInput = document.getElementById('autonomousProjectPrompt'); // Assuming this ID exists

            if (!autonomousPlanDisplay || !startButton || !stopButton || !projectPromptInput) break;

            let statusText = `<strong>Autonomous Plan: ${message.status.replace(/_/g, ' ')}</strong>`; // User-friendly status
            // Handle initial plan display clearing
            if (message.status === 'started' || message.status === 'planning') {
                if (message.status === 'planning') {
                    autonomousPlanDisplay.innerHTML = ''; // Clear previous plan details
                    statusText = "<strong>Autonomous Plan: Planner agent is thinking...</strong>";
                } else { // 'started'
                     const existingOverallStatus = autonomousPlanDisplay.querySelector('.overall-plan-status');
                     // Clear display only if it's a truly new plan start, not just more actions coming for an existing plan
                     if (!existingOverallStatus || (existingOverallStatus && !autonomousPlanDisplay.querySelector('.action-item'))) {
                            autonomousPlanDisplay.innerHTML = '';
                     }
                }
                // Update button states for an active plan
                startButton.disabled = true;
                stopButton.style.display = 'inline-block';
                projectPromptInput.disabled = true;
            }

            if (message.completedActions !== undefined && message.totalActions !== undefined) {
                statusText += ` (${message.completedActions} / ${message.totalActions} actions processed)`;
            }
            if (message.error) {
                statusText += `<br><span class="error-output">Error: ${sanitizeHTML(message.error)}</span>`;
            }

            // Get or create the overall status display div
            let overallStatusDiv = autonomousPlanDisplay.querySelector('.overall-plan-status');
            if (!overallStatusDiv) {
                overallStatusDiv = document.createElement('div');
                overallStatusDiv.className = 'message overall-plan-status';
                autonomousPlanDisplay.prepend(overallStatusDiv); // Add to the top of the plan display
            }
            overallStatusDiv.innerHTML = statusText; // Update with current status

            // Reset UI elements when plan ends (completed, error, cancelled)
            if (message.status === 'completed_all' || message.status === 'error' || message.status === 'cancelled_by_user' || message.status === 'failed_to_plan') {
                const autoModeEnabled = document.getElementById('autonomousModeStatus')?.textContent === 'Enabled';
                startButton.disabled = !autoModeEnabled; // Re-enable based on current settings
                stopButton.style.display = 'none';
                projectPromptInput.disabled = !autoModeEnabled;
            }
            autonomousPlanDisplay.scrollTop = 0; // Scroll to top to see the latest overall status
            break;
        }
        // Updates the UI for a specific action within an autonomous plan.
        case 'actionStatus': {
            if (!autonomousPlanDisplay) break;
            const actionDiv = getOrCreateActionElement(message.id, message.index, autonomousPlanDisplay);
            actionDiv.className = `action-item action-status-${message.status}`; // e.g., action-status-completed

            let statusIcon = '';
            switch(message.status) {
                case 'in_progress': statusIcon = '⏳'; break;
                case 'completed': statusIcon = '✅'; break;
                case 'failed': statusIcon = '❌'; break;
                case 'cancelled': statusIcon = '⏹️'; break;
                default: statusIcon = 'ℹ️'; break; // Should not happen if status is always one of the above
            }

            let outputHtml = '';
            if (message.output) {
                // Display output in a <pre> tag for formatting
                outputHtml = `<pre class="action-output">${sanitizeHTML(typeof message.output === 'string' ? message.output : JSON.stringify(message.output, null, 2))}</pre>`;
            } else if (message.message && message.status !== 'completed' && message.status !== 'in_progress' && message.status !== 'cancelled') {
                 // If there's a message for a failed/errored action and no specific output, show message as output
                 outputHtml = `<pre class="action-output error-output">${sanitizeHTML(message.message)}</pre>`;
            }

            // Construct detailed HTML for the action item
            actionDiv.innerHTML = `
                <div class="action-header">
                    <span class="action-index">[${message.index + 1}/${message.totalActions || '?'}]</span>
                    <span class="action-type">${sanitizeHTML(message.action)}</span>
                    <span class="action-status-icon">${statusIcon}</span>
                    <span class="action-description">${sanitizeHTML(message.description || '')}</span>
                </div>
                ${message.message && (message.status === 'completed' || message.status === 'in_progress') ? `<div class="action-message"><small>${sanitizeHTML(message.message)}</small></div>` : ''}
                ${outputHtml}
            `;
            autonomousPlanDisplay.scrollTop = autonomousPlanDisplay.scrollHeight; // Scroll to keep latest action visible
            break;
        }
        // Displays messages sent by an agent using the 'agent_message' action type.
        case 'displayAgentMessage':
            if (!autonomousPlanDisplay) break;
            const agentInfoMsgDiv = document.createElement('div');
            // Apply styling based on message_type (info, warning, error)
            agentInfoMsgDiv.className = `message agent-info-${message.type || 'info'}`;
            agentInfoMsgDiv.textContent = `[Agent Message]: ${sanitizeHTML(message.text)}`;
            autonomousPlanDisplay.appendChild(agentInfoMsgDiv);
            autonomousPlanDisplay.scrollTop = autonomousPlanDisplay.scrollHeight;
            break;
    }
});

/**
 * Dynamically adds action buttons (Copy, Insert, Replace, Save as New File)
 * beneath a given message div if its content is identified as a code block.
 * @param {HTMLElement} messageDiv The DOM element (usually a div containing an agent's message)
 *                                to which the action buttons will be appended.
 * @param {string} fullTextContent The full text content of the message, used to extract code.
 */
function addCodeActionButtons(messageDiv, fullTextContent) {
    // Regex to attempt to extract code from a Markdown code block (e.g., ```python\ncode\n```)
    // It captures the language (optional) and the code content.
    const codeBlockRegex = /```([a-zA-Z]*)\n([\s\S]*?)```/m;
    const match = codeBlockRegex.exec(fullTextContent);
    let codeToUse = fullTextContent; // Default to full text if no explicit block found
    let lang = ''; // Detected language from code block
    if (match && match[2]) {
        codeToUse = match[2].trim(); // Use only the content within the backticks
        lang = match[1] || ''; // Detected language, if specified
    } else if (fullTextContent.trim().startsWith('```') && fullTextContent.trim().endsWith('```')) {
        // Handle case where it's just the block without language and newlines, e.g. ```code```
        codeToUse = fullTextContent.trim().substring(3, fullTextContent.trim().length - 3).trim();
    }
    // else: it's not a recognized code block, but buttons might still be relevant if user thinks it's code.
    // For now, buttons are only added if ``` is detected.

    // Prevent adding buttons multiple times to the same message
    const existingActionsContainer = messageDiv.querySelector('.code-actions');
    if (existingActionsContainer) { return; }

    const actionsContainer = document.createElement('div');
    actionsContainer.className = 'code-actions';

    // --- Copy Code Button ---
    const copyButton = document.createElement('button');
    copyButton.textContent = 'Copy Code';
    copyButton.onclick = () => {
        navigator.clipboard.writeText(codeToUse).then(() => {
            vscode.postMessage({ command: 'showInfo', text: 'Code copied to clipboard!' });
        }, (err) => {
            vscode.postMessage({ command: 'showError', text: 'Failed to copy code: ' + err });
        });
    };
    actionsContainer.appendChild(copyButton);

    // --- Insert at Cursor Button ---
    const insertButton = document.createElement('button');
    insertButton.textContent = 'Insert at Cursor';
    insertButton.onclick = () => {
        vscode.postMessage({ command: 'applyCode', code: codeToUse, strategy: 'insertAtCursor' });
    };
    actionsContainer.appendChild(insertButton);

    // --- Replace Selection Button ---
    const replaceButton = document.createElement('button');
    replaceButton.textContent = 'Replace Selection';
    replaceButton.onclick = () => {
        vscode.postMessage({ command: 'applyCode', code: codeToUse, strategy: 'replaceSelection' });
    };
    actionsContainer.appendChild(replaceButton);

    // --- Save as New File Button ---
    const newFileButton = document.createElement('button');
    newFileButton.textContent = 'Save as New File...';
    newFileButton.onclick = () => {
        // Suggest a file extension based on the detected language, default to .txt
        const fileExtension = lang ? '.' + lang.toLowerCase() : '.txt';
        vscode.postMessage({ command: 'createFileWithCode', code: codeToUse, suggestedFileName: `agent-output${fileExtension}` });
    };
    actionsContainer.appendChild(newFileButton);

    messageDiv.appendChild(actionsContainer); // Append the buttons container to the message div
}
